services:
  - type: web
    name: soubayugami-kansokuki-v58
    env: node
    plan: free
    buildCommand: npm install --no-package-lock && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
